//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2a.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        public int Product_Id { get; set; }
        public string Product_Name { get; set; }
        public string Size { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> MfgDate { get; set; }
        public string Category { get; set; }
    }
}
